### ISSUE TITLE
Question 2 is worded wrong in lab

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-exponential-distribution-lab#1]
Question 2 in the lab is worded "The average student takes 44 minutes to complete a test. What is the probability that the fastest student in the class will take 38 minutes to complete the test?" 
But Question 2 in the solution is worded "The average student takes 44 minutes to complete a test. What is the probability that the fastest student in the class will take **more than** 38 minutes to complete the test?"

This completely changes how you answer the question.

**Comment by fpolchow** [comment]
Made master match solution. Thanks! :)
