### ISSUE TITLE
Question 4 is missing requirements in lab

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-exponential-distribution-lab#2]
Question 4 in the lab simply says "The average interval that calls come in at a call center is 8 seconds. What is the probability that the next**s** call will happen in 7 seconds?"
(flagging a typo for you)
Question 4 in the solutions is much broader: "The average interval that calls come in at a call center is 8 seconds. **Plot the probability density function for a call happening at each second between 0 and 30 seconds (you can look at intervals of 0.5 seconds only.** What is the probability that the next**s** call will happen in 7 seconds?"
(typo is there in the solution too)

**Comment by fpolchow** [comment]
Added what was in solution to master and fixed typo. Thanks for flagging! :)
